-- 02_tablas.sql
-- Modelo relacional de CampusCloud para PostgreSQL.

\connect "CampusCloud"

CREATE TABLE IF NOT EXISTS estudiantes (
  id_estudiante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula VARCHAR(20) NOT NULL UNIQUE,
  nombre VARCHAR(100) NOT NULL,
  correo VARCHAR(120) NOT NULL UNIQUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS servicios (
  id_servicio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_servicio VARCHAR(100) NOT NULL UNIQUE,
  descripcion TEXT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS solicitudes (
  id_solicitud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante INTEGER NOT NULL,
  id_servicio INTEGER NOT NULL,
  fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente',
  comentario TEXT,
  CONSTRAINT fk_solicitudes_estudiantes
    FOREIGN KEY (id_estudiante)
    REFERENCES estudiantes (id_estudiante)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_solicitudes_servicios
    FOREIGN KEY (id_servicio)
    REFERENCES servicios (id_servicio)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT chk_solicitudes_estado
    CHECK (estado IN ('Pendiente', 'En proceso', 'Aprobada', 'Rechazada', 'Cancelada'))
);

CREATE INDEX IF NOT EXISTS idx_solicitudes_estudiante
  ON solicitudes (id_estudiante);

CREATE INDEX IF NOT EXISTS idx_solicitudes_servicio
  ON solicitudes (id_servicio);

CREATE INDEX IF NOT EXISTS idx_solicitudes_estado
  ON solicitudes (estado);
