services:
  #===============================================================
  #==========================PostgresSQL
  #===============================================================
  postgres-claude:
    image: postgres:16-bookworm
    container_name: campusclaude-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campusclaude_net
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  #===============================================================
  #==========================Pgadmin
  #===============================================================
  pgadmin:
    image: dpage/pgadmin4:6.17
    container_name: campusclaude-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT _PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres-claude
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - campusclaude_net

#===============================================================
#==========================volumenes
#===============================================================
volumes:
  postgres_data:
    external: true
    name: ${POSTGRES_VOLUME}

  pgadmin_data:
    external: true
    name: ${PGADMIN_VOLUME}

#===============================================================
#==========================RED
#===============================================================
networks:
  campusclaude_net:
    external: true
    name: ${DOCKER_NETWORK}
